max-teleport: 50000 # Maximum teleport number for every coordinate
teleport-commands: # Add in lowercase!
  - tp
  - teleport
blocked-teleport-message: "§8§l┃ §cExploitFixer §8┃ §7You've reached the maximum teleport range"